-- MySQL Script generated by MySQL Workbench
-- Fri Sep 25 17:32:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema goit_rdb_hw_02
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema goit_rdb_hw_02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goit_rdb_hw_02` DEFAULT CHARACTER SET utf8 ;
USE `goit_rdb_hw_02` ;

-- -----------------------------------------------------
-- Table `goit_rdb_hw_02`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goit_rdb_hw_02`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit_rdb_hw_02`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goit_rdb_hw_02`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NOT NULL,
  `client_address` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit_rdb_hw_02`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goit_rdb_hw_02`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `client-order_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `client-order`
    FOREIGN KEY (`id_client`)
    REFERENCES `goit_rdb_hw_02`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit_rdb_hw_02`.`ordered_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goit_rdb_hw_02`.`ordered_products` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `product_quantity` INT NOT NULL,
  PRIMARY KEY (`id_order`, `id_product`),
  INDEX `product-ordered_products_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `order-ordered_products`
    FOREIGN KEY (`id_order`)
    REFERENCES `goit_rdb_hw_02`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product-ordered_products`
    FOREIGN KEY (`id_product`)
    REFERENCES `goit_rdb_hw_02`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
